// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4WlbPUN1OUyKC7QPItAOf8L0Eb3qKLRo',
    appId: '1:915309882566:android:dc4beb649c227ee2b3fbc7',
    messagingSenderId: '915309882566',
    projectId: 'taskmaster-flutter',
    storageBucket: 'taskmaster-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lYhAkxWKszIJGBwz9LfywiTj42kPkK4',
    appId: '1:915309882566:ios:842e06fa9cf4d37ab3fbc7',
    messagingSenderId: '915309882566',
    projectId: 'taskmaster-flutter',
    storageBucket: 'taskmaster-flutter.firebasestorage.app',
    iosBundleId: 'com.example.taskmasterFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu-AbjJz32SSfm78gT_4Cl3SywrMu82CE',
    appId: '1:915309882566:web:1f29d352b02d4397b3fbc7',
    messagingSenderId: '915309882566',
    projectId: 'taskmaster-flutter',
    authDomain: 'taskmaster-flutter.firebaseapp.com',
    storageBucket: 'taskmaster-flutter.firebasestorage.app',
  );
}
